### ISSUE TITLE
Telescope Simulator capabilities not saved

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#10]
The ASCOM Telescope Simulator for .NET has the ability to specify the capabilities of the simulated telescope. One of those capabilities is whether the telescope supports asynchronous equatorial slewing (CanSlewAsync). Another is whether the telescope driver supports the ApertureArea, Aperture Diameter and FocalLength properties (CanOptics).

These values exist on the setup dialog form as the Equatorial Asynchronous and Optics checkboxes, but when the user changes the checked state for those controls and closes the form with the OK button those values are never harvested from the form and saved to the simulator's profile or reflected in the behavior of the simulator.

**Comment by Peter-Simpson** [comment]
Thanks for reporting this. I've updated the telescope simulator to persist the checkbox values and act on the configuration as set.

The fix will be in the next Platform release so I'm closing this issue.
