### ISSUE TITLE
ASCOM Dome Control Panel Run-time error

### ISSUE THREAD

**Issue by jp-technology** [ASCOMInitiative/ASCOMPlatform#13]
Hi, 

When using Sequence Generator PRO, the Observatory will occasionally disconnect and a message box titled "ASCOM Dome Control Panel" will appear containing the following lines of text:
_____________________________________________

Run-time error '-2147352567 (80020009)':

Unable to complete command
_____________________________________________

Clicking OK causes the ASCOM Dome Control Panel to disappear from the screen. I can then click reconnect in SGP and the control panel will restart, but often the dome will likely have closed before I've realized the ASCOM Dome CP crashed and any exposures in progress need to be restarted.

The dome being controlled is a MaxDome II

I am using the latest 6.4.1.2695 ASCOM platform release.

If there are any system logs that you can direct me to I would be happy to provide them.

Thanks,

John

**Comment by astroman133** [comment]
You should probably post this issue on the ASCOM-Talk forum. Then others can provide troubleshooting advice. If your issue turns out to be something that is addressable within the Platform or the Dome Control Panel it would be appropriate to post the details of the issue here.

**Comment by NameOfTheDragon** [comment]
My view on this is that there's not really any point in having 3 different scope-dome hubs in the platform. Given that both the Dome Control Panel and POTH predate the changes to `SideOfPier`, neither of them really work properly any more and they are effectively not maintainable, being written in VB6. In due course, it might be an idea to retire POTH and Dome Control Panel and replace both with the newer Device Hub, which does work correctly with the new definition of `SideOfPier`

**Comment by Peter-Simpson** [comment]
I'm closing this issue because the new Device Hub will be added to the Platform 6.5 release that will be delivered in the next one to two months.
