### ISSUE TITLE
Current DriverAccess library does not work with drivers written in .Net Core

### ISSUE THREAD

**Issue by DanielVanNoord** [ASCOMInitiative/ASCOMPlatform#16]
Net Core 3.0 ArrayLists are not COM Visible so direct casting does not work. .Net Core only exposes ArrayLists over COM as IEnumerble. CoreFX has chosen not to fix this, see: https://github.com/dotnet/corefx/issues/40675.

**Comment by Peter-Simpson** [comment]
I'm closing this issue as it will be in the Platform 6.5 release that will be delivered in the next one to two months.
