### ISSUE TITLE
Wrong spelling in Switch template

### ISSUE THREAD

**Issue by iwannabswiss** [ASCOMInitiative/ASCOMPlatform#18]
In the Validate sub statement for the Switch template that checks that the number of states for the switch is correct, wrong is misspelled.

 TL.LogMessage(message, String.Format("Switch {0} has the wriong number of states", id, ns))

**Comment by Peter-Simpson** [comment]
Hi,

Thanks for logging this, I've corrected the spelling and the fix will be in the next release.

Regards, Peter

**Comment by Peter-Simpson** [comment]
I'm closing this issue because it is fixed and will be in the next release, which will be delivered in the next one to two months.
