### ISSUE TITLE
Inno Setup v5 to v6 issue re MinVersion=

### ISSUE THREAD

**Issue by brownrb** [ASCOMInitiative/ASCOMPlatform#21]
The ASCOM script generator seems to insert
MinVersion=0,5.0.2195sp4
which INNO v6 rejects. Commenting this out lets the script ignore this. I am not sure what this should be set to.

**Comment by Peter-Simpson** [comment]
I'm closing this issue because I've revised the driver installer master template and the fix will be in the next release, which will be in the next one to two months
