### ISSUE TITLE
Add PulseGuide method Note

### ISSUE THREAD

**Issue by rmorgan001** [ASCOMInitiative/ASCOMPlatform#25]
Please add "May raise an error if the telescope is not tracking or is slewing" or something similar to  the developer help guide for the PulseGuide method.  This can be used for Telescope drivers that may not want to complete a PulseGuide command while slewing or not tracking and want to return an error to the calling application.

**Comment by Peter-Simpson** [comment]
I'm closing this issue as it will be in the Platform 6.5 release that will be delivered in the next one to two months.
