### ISSUE TITLE
Focuser simulator GUI not response.

### ISSUE THREAD

**Issue by fockez** [ASCOMInitiative/ASCOMPlatform#27]
When using comtypes to connect Focuser .Net simulator, the GUI will be shown, but always Not responding, the API works fine. All the other simulator works fine.
Thanks.

**Comment by Peter-Simpson** [comment]
Hi focez,

I'm sorry there is not enough information in your post to be able to help you. To me this sounds more like a "How do I do this" request than an issue with the Platform, which is what this Issues log is for. 

Please can you post on the [Developer Forum Link](https://ascomtalk.groups.io/g/Developer) providing a simple example of the code you are using, there are several active developers who will be able to assist there.

I'm going to close this issue but am happy to re-open it if we identify a Platform fault while diagnosing the issue that you are seeing.

Regards, Peter
