### ISSUE TITLE
Enhance Telescope Simulator for .NET

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#30]
The DestinationSideOfPier method is apparently optional because of comments that indicate that it could throw a MethodNotImplemented exception. However, there is no way to simulate or test this behavior except through a driver that exhibits this behavior. It would be helpful for the simulator to be able to optionally throw MethodNotImplemented exception as a result of calls to DestinationSideOfPier to allow application developers to have confidence that they are handling this type of "weak" driver correctly. One of these drivers is the Software Bisque 2X Telescope Driver.

Thanks!

**Comment by Peter-Simpson** [comment]
I've added a new DestinationSideofPier enable / disable checkbox to the Telescope Simulator setup as requested. I've also fixed the SideofPier property that I found was not respecting it's setup enable / disable checkbox setting. These changes will be in the Platform 6.5 release.

**Comment by astroman133** [comment]
Thanks, Peter. I closed the issue.
