### ISSUE TITLE
imagearray documentation update

### ISSUE THREAD

**Issue by msproul** [ASCOMInitiative/ASCOMPlatform#36]
As per Rick B. this web page needs to be updated

https://ascom-standards.org/Help/Developer/html/P_ASCOM_DeviceInterface_ICameraV2_ImageArray.htm

It states that the return code for no image data avaiable is NOT CONNECTED,  it is supposed to be INVALID OPERATION.

Additionally there is a typo on the page,  " iamges"  >> "images"

Thanks
Mark

**Comment by msproul** [comment]
this also applies to imagearrayvariant

**Comment by Peter-Simpson** [comment]
Hi Mark,

Thanks for reporting this, I've corrected the descriptions and they will be in the upcoming Platform 6.5 release.

Best wishes, Peter
