### ISSUE TITLE
Typographical error in Platform Developer Help document

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#37]
From the help document's table of contents, clicking on the ASCOM.DriverAccess Dome Class topic brings up a document that displays the name and description of the Constructor, along with all the Properties and Methods of the class. Under Properties, the description of the CanPark property says "True if driver is capable of setting dome altitude." This is incorrect. if you drill down to the page for that property (Dome.CanPark) you see the same description.

The same error does not exist in the description of the IDomeV2.CanPark property description.

![screenshot](https://user-images.githubusercontent.com/33786208/86037267-f2ce0180-b9f3-11ea-88bb-2277b96652cf.png)

**Comment by Peter-Simpson** [comment]
Thanks for reporting this Rick, I've copied Tim's revised IDomeV2 wording to DriverAccess and this has also fixed the issue that you reported. The update will be in the Platform 6.5 release so I'm closing the issue.

Thanks, Peter
