### ISSUE TITLE
Documentation error in Alpaca Reference API document

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#39]
In Section 2.8.3 ASCOM Reserved Error Numbers, the values in the COM Exception Numbers column appear to have one too many digits. For example, 0x800400400 should be 0x080040400.

Screenshot attached.

![Alpaca API PDF](https://user-images.githubusercontent.com/33786208/95218685-5f059180-07a9-11eb-92df-564382779129.png)

**Comment by astroman133** [comment]
I re-read my explanation of the issue and saw that I too had put too many zeros into my explanation. The sentence in question should read: **For example, 0x800400400 should be 0x80040400.** Thanks!

**Comment by Peter-Simpson** [comment]
Thanks Rick, I've corrected the documentation, it will go out in the next ASCOM Remote Release.
