### ISSUE TITLE
Developer Document error

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#42]
The ASCOM 6.5 Developer Document needs to be corrected for the ICameraV3.InterfaceVersion. The documentation indicates that the property should return "2" for this interface version. This should be corrected to "3".

Thanks!

**Comment by Peter-Simpson** [comment]
Thanks Rick, I've corrected the text and the fix will be in the 6.5SP1 release.

Best wishes, Peter
