### ISSUE TITLE
Consider documentation change to ICameraV3.SensorName property

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#44]
The Platform Developer help for ASCOM.DeviceInterface.ICameraV3.SensorName says that it is "Mandatory must return an empty string if the sensor is unknown". 

In the Remarks section it says "May throw a PropertyNotImplementedException if the sensor's name is not known."

ASCOM.DriverAccess.Camera.SensorName has no guidance about the fact that an empty string could be returned or that the property is optional.

**Comment by Peter-Simpson** [comment]
Closing as fixed.
