### ISSUE TITLE
Driver Template ReadMe file 404 error

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#45]
When using the ASCOM Templates to create a skeleton driver, one of the created files is ReadMe.htm. For an in-process driver that ReadMe file contains the following statement very near to the top of the file:

Prior to developing your first driver, please familiarize yourself with the developer information we've provided at the ASCOM Initiative web site (internet required). 

Part of that text is a link to a developer.html page on the ASCOM-Standards web site. Clicking on this link generates a page not found error. I believe that instead the link should be "https://ascom-standards.org/Developer/Index.htm".

**Comment by Peter-Simpson** [comment]
Thanks Rick, I've fixed the template links.

Best wishes, Peter
