### ISSUE TITLE
Observing Conditions Hub Tester Chooser Issue

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#49]
The Observing Conditions Hub includes a test program. The program has a Chooser button that launches the Chooser to select an Observing Conditions driver. However, the user's selection is not honored and it appears that only it can only test the OC Hub.

I recommend that either the Choose button be removed, but keep the Setup button, or if the test program is suitable, allow it to be used as a test client program for any OC driver.

**Comment by Peter-Simpson** [comment]
Thanks for reporting this Rick, I've removed the Chooser button and tidied the code. The fix will be in the SP2 release.

Best wishes, Peter
