### ISSUE TITLE
Update IDomeV2 documentation to reflect async design principles

### ISSUE THREAD

**Issue by ghilios** [ASCOMInitiative/ASCOMPlatform#51]
See the discussion from the mailing list for extra context: https://ascomtalk.groups.io/g/Developer/topic/80764828?p=Created,,,20,2,0,0

Please update the IDomeV2 documentation to reflect async design principles, particularly with respect to:
- Slewing property following shutter operations, dome rotation, and parking
- ShutterStatus following OpenShutter and CloseShutter

At the moment there's been confusion between application developers and driver developers regarding what should happen after an async method returns to the caller. In particular, it should:

- Raise an exception if the operation isn't going to take place
- Corresponding status property reflects an inprogress or completed state immediately

Without this, applications may need to poll and wait to see if progress takes place which is a violation of design principles.

**Comment by Peter-Simpson** [comment]
Closing this issue because our async principles are provided here [https://www.ascom-standards.org/newdocs/async-faq.html](https://www.ascom-standards.org/newdocs/async-faq.html).
