### ISSUE TITLE
Telescope Simulator returns incorrect DriverVersion

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#56]
The Telescope Simulator for .NET returns its AssemblyVersion for its DriverVersion. Currently this is '6.6.0.0'.

The documentation states that it must only contain the major and minor versions and be of the format 'n.n'.
Clearly the string returned by the simulator is incorrect.

Also Conform does not validate this and does not raise an error when '6.6.0.0' is returned.

The Alpyca package tries to validate the version value returned from the Simulator, via ASCOM Remote, as a float. This fails and it raises an exception to the caller.

**Comment by Peter-Simpson** [comment]
Hi Rick,

Thanks for reporting this, I've fixed the simulator and updated Conform to perform a more rigorous test. I've checked all the other Platform simulators and none of them had a similar version number issue.

Best wishes, Peter
