### ISSUE TITLE
Conform and Telescope Simulator errors

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#57]
The ASCOM Telescope Simulator has a setup setting called "Tracking Rates". When this option is checked, the Simulator supports all 4 possible drive rate values. However, if Tracking Rates is unchecked, the only supported rate is driveSidereal. However, no InvalidValueException is raised when an attempt is made to set to set the tracking rate to an unsupported value.

In addition, since Conform only tests supported rates, no error is generated by Conform that says that the Simulator is non-conformant.

**Comment by Peter-Simpson** [comment]
The issue has been fixed with changes to the Platform, OmniSims and Conform Universal.
