### ISSUE TITLE
Conform Issue with Telescope Simulator

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#6]
When running Conform against the ASCOM.Simulator.Telescope driver, an issue with PulseGuide is reported when dual axis pulse guiding is deselected in the driver properties. Disabling dual axis pulse guiding is supposed to indicate that calls to PulseGuide are synchronous. This should mean that Conform should never see IsPulseGuiding as True. However, the following output is generated by Conform.

08:33:22.193 PulseGuide                        ISSUE    Synchronous pulseguide expected but IsPulseGuiding has returned TRUE

**Comment by Peter-Simpson** [comment]
Thanks for reporting this. The simulator was waiting for the correct period of time, creating a synchronous call, but did not clear the RA and DEC IsPulseGuiding flags before returning to the client application. This gave rise to the Conform issue report.

The fix will be in the next Platform release so I'm closing the issue.

Regards, Peter
