### ISSUE TITLE
Reconsider Usage of Dome Component "slave" Terminology

### ISSUE THREAD

**Issue by michealroberts** [ASCOMInitiative/ASCOMPlatform#60]
As the title suggests, although a legacy of the computer industry as a whole, we should look to deprecate the usage of slave terminology in the Dome component.

I would suggest any of the following:

- following
- twinned
- mirroring
- parallelling
- **coupled**

**Comment by Peter-Simpson** [comment]
Hi Micheal,

I raised your suggestion at the ASCOM Core Group meeting yesterday. One of ASCOM's cornerstones is absolute "backward compatibility", which, at times, does constrain our ability to change interfaces. The Slaved and CanSlave properties have been in use for 10 to 15 years and are hard wired into all Dome applications and drivers. We can't simply remove these members from the interface without breaking every Dome driver and application that works with Dome devices.

We also discussed adding duplicate properties with different names but this seemed to have little value given that we can't remove the existing members.

Consequently, we don't plan to take your thoughtful and considerate suggestion further.

Best wishes, Peter
