### ISSUE TITLE
Correct documention of Camera.AbortExposure

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/ASCOMPlatform#63]
Due to the existence of CanAbortExposure, it follows that AbortExposure, in both DeviceInterface.ICameraV3 and DriverAccess.Camera, should be an Optional method and should raise a NotImplemented exception if called when CanAbortExposure is False.

**Comment by Peter-Simpson** [comment]
Hi Rick,

Thanks for reporting the issue, I've updated the help in the Platform and Library to match. The changes will be in the next release.

Best wishes, Peter
