### ISSUE TITLE
Camera.SensorName test confusion

### ISSUE THREAD

**Issue by RReverser** [ASCOMInitiative/ASCOMPlatform#65]
I noticed that ConformU requires SensorName to be implemented (in my case it's not because I can't get sensor name).

I went to double-check the ASCOM docs and noticed a discrepancy that I think led to my initial confusion:
![image](https://user-images.githubusercontent.com/557590/232344712-7d6f6ed0-bac7-4583-b694-41c9b7ad85a1.png)

It simultaneously says "Must throw an exception if not supported." in the Exceptions section and "Must return an empty string if the sensor name is not known." in the Remarks section.

I'm guessing the Remarks are correct, but then the Exceptions section of the docs contains a mistake and should be updated.

**Comment by Peter-Simpson** [comment]
Closing because his is fixed in the Platform and Library. It was already correct in the master interface definition document.
