### ISSUE TITLE
ASCOM Platform 6.6 - Service Pack 2 breaks ASCOM Remote - Version 6.7.1+4785

### ISSUE THREAD

**Issue by ShinobiSlayer** [ASCOMInitiative/ASCOMPlatform#68]
ASCOM Platform 6.6 - Service Pack 2 breaks ASCOM Remote - Version 6.7.1+4785

As far as I can see after upgrading to ASCOM Platform 6.6 - Service Pack 2 Ascom Remote - Version 6.7.1+4785 no longer abides by https://ascom-standards.org/api/

When a request for /api/v1/switch/0/getswitchname or /api/v1/switch/0/getswitchvalue is called it no longer passes the switch ID as a request param.

6.6 SP2
clientId, clientTransactionId, deviceNumber, ID
26863, 5056, 0, null

vs

6.6 SP1
clientId, clientTransactionId, deviceNumber, ID
2128, 1967, 0, 16

**Comment by Peter-Simpson** [comment]
Hi,

I'm not clear on exactly what you saying is not working. I have just confirmed that this URL works OK with ASCOM Remote:

> http://127.0.0.1:11111/api/v1/switch/0/getswitchdescription?Id=1

and that I get a complete Conform pass when I an ASCOM Remote Switch device. through an Alpaca Dynamic Client

Please can you be clearer about exactly what you are doing that isn't working?

Best wishes, Peter

**Comment by ShinobiSlayer** [comment]
The request parameter ID has become Id in SP2

**Comment by Peter-Simpson** [comment]
Hi,

We've received several reports of problems caused by the Id/ID case switch in the Platform and are urgently investigating whether we need to switch back to the original ID casing. Please keep an eye on the ASCOM Developer forum for an announcement.

Best wishes, Peter
